---
title: "Celligner plots for CCLF RNA full model characterization only"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

Ran using `Celligner_methods_with_CCLF.R`  and results are saved to subfolder `celligner_runs > plus_cclf_rnaseq_20201005`
```{r}
library(here)
library(magrittr)
library(tidyverse)
library(data.table) # for fread
source(here::here('src', 'Celligner_helpers.R'))
source(here::here('src', 'analysis_helpers.R'))
source(here::here('src', 'global_params.R'))
source(here::here('src', 'Figure2.R'))

source("/Users/gmiller/Documents/Work/GitHub/helper.R")

library(useful)
```

```{r}
results_dir = "celligner_runs/plus_cclf_rnaseq_20201005/results/"
# Load in pre-computed data
cclf_subset <- readRDS('/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/results/only_full_characterization_v2_comb_obj.rds')

```


```{r plot functions}
# Figure 2: all data combined
Celligner_alignment_plot <- function(alignment) {
  Celligner_alignment <- ggplot2::ggplot(alignment, 
                                         ggplot2::aes(UMAP_1, UMAP_2, fill=lineage, size= type, color = type)) +
    ggplot2::geom_point(alpha=0.6, pch=21)  +
    ggplot2::scale_color_manual(values=c(`CL`='black', `tumor`='white', `CCLF` = 'red')) +
    ggplot2::scale_size_manual(values=c(`CL`=0.9, `tumor`=0.75, `CCLF` = 1)) +
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = 'bottom', 
          text=ggplot2::element_text(size=8),
          legend.margin =ggplot2::margin(0,0,0,0)) +
    ggplot2::guides(fill=FALSE, color=FALSE) +
    ggplot2::scale_fill_manual(values=tissue_colors) +
    ggplot2::xlab("UMAP 1") +
    ggplot2::ylab("UMAP 2")
  
  return(Celligner_alignment)
}


```

```{r}
# Create full annotations df for TCGA, DepMap, and CCLF combined
annotation_file = 'Celligner_info.csv'
data_dir = "celligner_runs/plus_cclf_rnaseq_20201005"
# ann <- data.table::fread(file.path(data_dir, annotation_file)) %>% as.data.frame()
ann <- data.table::fread("/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/Celligner_info.csv") %>% as.data.frame()
if('UMAP_1' %in% colnames(ann)) {
  ann <- ann %>% 
    dplyr::select(-UMAP_1)
}
if('UMAP_2' %in% colnames(ann)) {
  ann <- ann %>% 
    dplyr::select(-UMAP_2)
}
if('cluster' %in% colnames(ann)) {
  ann <- ann %>% 
    dplyr::select(-cluster)
}

corner(ann)


# Read in CCLF metadata
cclfmeta <- data.table::fread('/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/rna_metadata_for_celligner_full_characterization_only.csv') %>% as.data.frame()

# TODO: we are missing the sample "SM-E9H91" because it doesn't have any lineage information in the RP Tracker.. ask Moony?
cclfdisease <- data.table::fread("/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/rna_celligner_diseases.csv") %>% as.data.frame() %>% dplyr::rename("bsp_sample_id_rna"=`Sample ID`, lineage = "Celligner disease annotation (Moony)")

cclfmeta <- cclfmeta %>% dplyr::left_join(cclfdisease) %>% 
  dplyr::select(sampleID, `Primary/Metastasis` = tumor_subtype, lineage)

# Now, merge into the main ann df (aka add it!)
# This is now the combined annotations for all TCGA, DepMap, and CCLF samples. (TODO: actually, I think I'm using Allie's Celligner_info.csv metadata. May not have all current DepMap lines annotated.)
# ann <- ann %>% dplyr::full_join(cclfmeta, by = c("sampleID"))

test <- ann %>% dplyr::bind_rows(cclfmeta)
# TODO: using this as of 10/11/2020
ann <- test %>% dplyr::mutate(type = ifelse(sampleID %in% cclf_terra_ids, 'CCLF', type))

# TODO: take care of issue (using 20Q2 vs Allie's 19Q4) by merging with existing Seurat annotations (37 "missing" in 19Q4 compared to 20Q2. Aka 37 CCLE lines without any annotations... should probably fix if I have the time. TODO:)
tmp <- cclf_subset@meta.data
# tmp <- tmp %>% dplyr::select(sampleID, type, seurat_clusters, lineage, subtype, disease, `Primary/Metastasis`) %>% 
  # dplyr::bind_rows()


tmp2 <- tmp %>% dplyr::full_join(ann)

# Now, we should have the same number of rows in:
dim(tmp)
dim(cclf_subset@meta.data)

# Add a column to distinguish CCLF samples from everything else (e.g. tumor, CL, CCLF)
cclf_terra_ids <- data.table::fread("/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/rna_terra_ids_full_characterization_only.csv") %>% as.data.table() %>% .$sampleID 
tmp <- tmp %>% dplyr::mutate(type = ifelse(sampleID %in% cclf_terra_ids, 'CCLF', type))

# If so, can set ann <- tmp, and merge the annotations into aligned dataset. And then we start plotting!
ann <- tmp

```

```{r}
# Data wrangling

## Update annotations prior to plotting
alignment <- cclf_subset$umap@cell.embeddings

# Add metadata to the alignment data
dPlot <- mat_to_tibble(alignment, "sampleID") %>% 
  left_join(ann, by=c("sampleID" = "sampleID"))

```


```{r basic celligner plot}
Celligner_basic_plot <- function(alignment) {
  Celligner_alignment <- ggplot2::ggplot(alignment, 
                                         ggplot2::aes(UMAP_1, UMAP_2, fill=lineage)) +
    ggplot2::geom_point(alpha=0.6, pch=21)  +
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = 'bottom', 
          text=ggplot2::element_text(size=8),
          legend.margin =ggplot2::margin(0,0,0,0)) +
    ggplot2::guides(fill=FALSE, color=FALSE) +
    ggplot2::scale_fill_manual(values=tissue_colors) +
    ggplot2::xlab("UMAP 1") +
    ggplot2::ylab("UMAP 2")
  
  return(Celligner_alignment)
}
```
```{r}
write.csv(ann, "/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/results/metadata.csv",  row.names=FALSE)

write.csv(dPlot, "/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/results/aligned_data_with_metadata.csv",  row.names=FALSE)
```


```{r figure2 plot}
# Plot of everything.
Celligner_basic_plot(dPlot) + 
  ggtitle("Celligner UMAP embedding")

Celligner_alignment_plot(dPlot) + 
  ggtitle("Celligner UMAP embedding")

```
```{r}
# Make basic Celligner UMAP with set shapes and outlines for CL vs tumors.
Celligner_base_plot <- function(alignment){
  ggplot2::ggplot(alignment,
                           ggplot2::aes(UMAP_1, UMAP_2, shape=type, color = type)) +
    ggplot2::scale_color_manual(values=c(`CL`='black', `tumor`='gray', `CCLF` = "black")) +
    ggplot2::scale_shape_manual(values=c(`CL`=24, `tumor`=23, `CCLF` =21 )) +
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = 'bottom', 
          text=ggplot2::element_text(size=8),
          legend.margin =ggplot2::margin(0,0,0,0)) +
    ggplot2::guides(fill=FALSE, color=FALSE) +
    ggplot2::xlab("UMAP 1") +
    ggplot2::ylab("UMAP 2")
}
```


```{r}
# dPlot <- dPlot %>% dplyr::mutate(isCCLF = ifelse(type == "CCLF", TRUE, FALSE))
t <- Celligner_base_plot(dPlot) 

t<- t + ggplot2::aes(UMAP_1, UMAP_2, fill=lineage, alpha=isCCLF, size = type) + # normally, I'd include size=is_osteo
  ggplot2::geom_point() +
  ggplot2::scale_size_manual(values = c(`TRUE`=5, `FALSE`=0.2)) + 
  ggplot2::scale_alpha_manual(values = c(`FALSE`=0.2, `TRUE`=0.9)) +
  ggplot2::scale_fill_manual(values=tissue_colors)
t

ggsave(file="/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/results/celligner_cclf_bold.png", plot=t, width=10, height=8)

quickSavePlot("celligner_cclf_bold", png_not_pdf = T, add_to_pptx = F, image_dir = "/Users/gmiller/Documents/Work/GitHub/celligner_tasks/celligner_runs/plus_cclf_rnaseq_20201005/results")
```


```{r}

t <- ggplot2::ggplot(dPlot, ggplot2::aes(UMAP_1, UMAP_2, fill=lineage,shape = type)) +
    ggplot2::geom_point(alpha=0.2)  +
    # ggplot2::scale_size_manual(values=c(`CL`=0.9, `tumor`=0.7, `CCLF` = 1.0)) +
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = 'bottom', 
          text=ggplot2::element_text(size=8),
          legend.margin =ggplot2::margin(0,0,0,0)) +
    ggplot2::guides(fill=FALSE, color=FALSE) +
    ggplot2::scale_fill_manual(values=tissue_colors) +
    ggplot2::xlab("UMAP 1") +
    ggplot2::ylab("UMAP 2")
t

t <- ggplot2::ggplot(dPlot, ggplot2::aes(UMAP_1, UMAP_2, fill=lineage, shape = type)) +
    ggplot2::geom_point(alpha=0.2, pch=21)  +
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = 'bottom', 
          text=ggplot2::element_text(size=8),
          legend.margin =ggplot2::margin(0,0,0,0)) +
    ggplot2::guides(fill=FALSE, color=FALSE) +
    ggplot2::scale_fill_manual(values=tissue_colors) +
    ggplot2::xlab("UMAP 1") +
    ggplot2::ylab("UMAP 2")
t
```


```{r}
t <- ggplot2::ggplot(dPlot, ggplot2::aes(UMAP_1, UMAP_2, fill=lineage)) +
    ggplot2::geom_point(alpha=0.6, pch=21)  +
    ggplot2::theme_classic() + 
    ggplot2::theme(legend.position = 'bottom', 
          text=ggplot2::element_text(size=8),
          legend.margin =ggplot2::margin(0,0,0,0)) +
    ggplot2::guides(fill=FALSE, color=FALSE) +
    ggplot2::scale_fill_manual(values=tissue_colors) +
    ggplot2::xlab("UMAP 1") +
    ggplot2::ylab("UMAP 2")
t
```

```{r zoomed in plots}
# See Figure 4 code for examples of zooming in nicely
```